#!/bin/bash
#
# NISystem Opto22 Node Installer
# Run this script on the groov EPIC/RIO to set up automatic startup
#
# Usage:
#   ./install.sh <NISYSTEM_PC_IP> [NODE_ID] [API_KEY]
#
# Example:
#   ./install.sh 192.168.1.100
#   ./install.sh 192.168.1.100 opto22-002
#   ./install.sh 192.168.1.100 opto22-002 your-api-key
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=============================================="
echo "  NISystem Opto22 Node Installer"
echo "=============================================="
echo ""

# Check arguments
if [ -z "$1" ]; then
    echo -e "${RED}Error: NISystem PC IP address required${NC}"
    echo ""
    echo "Usage: $0 <NISYSTEM_PC_IP> [NODE_ID] [API_KEY]"
    echo ""
    echo "Example: $0 192.168.1.100"
    echo "         $0 192.168.1.100 opto22-002"
    exit 1
fi

MQTT_BROKER="$1"
NODE_ID="${2:-opto22-001}"
API_KEY="${3:-}"
INSTALL_DIR="/home/dev/nisystem"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Configuration:"
echo "  NISystem PC (MQTT Broker): $MQTT_BROKER"
echo "  Node ID: $NODE_ID"
echo "  Install directory: $INSTALL_DIR"
if [ -n "$API_KEY" ]; then
    echo "  API Key: (configured)"
fi
echo ""

# Check for Python 3
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python 3 is required but not installed${NC}"
    exit 1
fi

# Create install directory
echo -e "${YELLOW}Creating install directory...${NC}"
mkdir -p "$INSTALL_DIR"

# Copy Python script
echo -e "${YELLOW}Copying Opto22 node service...${NC}"
cp "$SCRIPT_DIR/opto22_node.py" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/opto22_node.py"

# Install Python dependencies
echo -e "${YELLOW}Installing Python dependencies...${NC}"
pip3 install --user paho-mqtt requests 2>/dev/null || {
    echo -e "${YELLOW}pip3 not available, trying pip...${NC}"
    pip install --user paho-mqtt requests 2>/dev/null || {
        echo -e "${RED}Warning: Could not install dependencies automatically${NC}"
        echo "Please install manually: pip install paho-mqtt requests"
    }
}

# Create environment file
echo -e "${YELLOW}Creating configuration...${NC}"
cat > "$INSTALL_DIR/opto22_node.env" << EOF
# Opto22 Node Configuration
# Generated by install.sh on $(date)

# MQTT Broker - NISystem PC
MQTT_BROKER=$MQTT_BROKER

# MQTT Port
MQTT_PORT=1883

# Node ID
NODE_ID=$NODE_ID

# groov API Key (optional - for authenticated REST API access)
API_KEY=$API_KEY
EOF

# Configure journald to limit log size (prevents flash wear)
echo -e "${YELLOW}Configuring log rotation (50MB max)...${NC}"
if [ -d "/etc/systemd/journald.conf.d" ] || mkdir -p /etc/systemd/journald.conf.d 2>/dev/null; then
    cp "$SCRIPT_DIR/journald-nisystem.conf" /etc/systemd/journald.conf.d/nisystem.conf 2>/dev/null || {
        echo -e "${YELLOW}Could not configure journald (may need root)${NC}"
    }
    systemctl restart systemd-journald 2>/dev/null || true
fi

# Install systemd service
echo -e "${YELLOW}Installing systemd service...${NC}"
sudo cp "$SCRIPT_DIR/opto22_node.service" /etc/systemd/system/ 2>/dev/null || {
    cp "$SCRIPT_DIR/opto22_node.service" /etc/systemd/system/
}
systemctl daemon-reload

# Enable and start service
echo -e "${YELLOW}Enabling service to start on boot...${NC}"
systemctl enable opto22_node.service

echo -e "${YELLOW}Starting service...${NC}"
systemctl start opto22_node.service

# Wait a moment and check status
sleep 2

echo ""
echo "=============================================="
if systemctl is-active --quiet opto22_node.service; then
    echo -e "${GREEN}SUCCESS! Opto22 Node is running${NC}"
else
    echo -e "${RED}WARNING: Service may not be running correctly${NC}"
fi
echo "=============================================="
echo ""
echo "Useful commands:"
echo "  Check status:   systemctl status opto22_node.service"
echo "  View logs:      journalctl -u opto22_node.service -f"
echo "  Restart:        systemctl restart opto22_node.service"
echo "  Stop:           systemctl stop opto22_node.service"
echo ""
echo "Configuration file: $INSTALL_DIR/opto22_node.env"
echo "Edit this file to change MQTT broker or node ID"
echo ""
echo "Log rotation: 50MB max, 7 days retention"
echo ""
