@echo off
setlocal enabledelayedexpansion

echo ================================================
echo   NISystem cRIO Deployment Script
echo ================================================
echo.

:: Check arguments
if "%~1"=="" (
    echo Usage: deploy_crio.bat ^<CRIO_IP^> [NISYSTEM_PC_IP] [NODE_ID]
    echo.
    echo   CRIO_IP       - IP address of the cRIO (required)
    echo   NISYSTEM_PC_IP - IP of this PC for MQTT (default: auto-detect)
    echo   NODE_ID       - Unique ID for this cRIO (default: crio-001)
    echo.
    echo Example:
    echo   deploy_crio.bat 192.168.1.50
    echo   deploy_crio.bat 192.168.1.50 192.168.1.100 crio-002
    exit /b 1
)

set CRIO_IP=%~1
set NISYSTEM_PC_IP=%~2
set NODE_ID=%~3

:: Default node ID
if "%NODE_ID%"=="" set NODE_ID=crio-001

:: Auto-detect PC IP if not provided
if "%NISYSTEM_PC_IP%"=="" (
    echo Detecting local IP address...
    for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4"') do (
        for /f "tokens=1" %%b in ("%%a") do (
            if not defined NISYSTEM_PC_IP set NISYSTEM_PC_IP=%%b
        )
    )
    :: Trim leading space
    set NISYSTEM_PC_IP=!NISYSTEM_PC_IP: =!
)

echo.
echo Configuration:
echo   cRIO IP:        %CRIO_IP%
echo   NISystem PC IP: %NISYSTEM_PC_IP%
echo   Node ID:        %NODE_ID%
echo.

:: Check if SCP is available
where scp >nul 2>&1
if errorlevel 1 (
    echo ERROR: SCP not found. Please install OpenSSH or use PuTTY's pscp.
    echo.
    echo On Windows 10/11, enable OpenSSH:
    echo   Settings ^> Apps ^> Optional Features ^> Add OpenSSH Client
    exit /b 1
)

set SCRIPT_DIR=%~dp0
set CRIO_NODE_DIR=%SCRIPT_DIR%services\crio_node

:: Check if source directory exists
if not exist "%CRIO_NODE_DIR%" (
    echo ERROR: crio_node directory not found at %CRIO_NODE_DIR%
    exit /b 1
)

echo.
echo Step 1: Creating deployment package...
echo ----------------------------------------

:: Create temp directory for deployment
set DEPLOY_DIR=%TEMP%\crio_deploy_%RANDOM%
mkdir "%DEPLOY_DIR%" 2>nul

:: Copy files
copy "%CRIO_NODE_DIR%\crio_node.py" "%DEPLOY_DIR%\" >nul
copy "%CRIO_NODE_DIR%\requirements.txt" "%DEPLOY_DIR%\" >nul
copy "%CRIO_NODE_DIR%\crio_node.service" "%DEPLOY_DIR%\" >nul
copy "%CRIO_NODE_DIR%\install.sh" "%DEPLOY_DIR%\" >nul

:: Create customized .env file with the PC's IP
echo # cRIO Node Configuration > "%DEPLOY_DIR%\crio_node.env"
echo # Generated by deploy_crio.bat on %date% %time% >> "%DEPLOY_DIR%\crio_node.env"
echo. >> "%DEPLOY_DIR%\crio_node.env"
echo # MQTT Broker - NISystem PC >> "%DEPLOY_DIR%\crio_node.env"
echo MQTT_BROKER=%NISYSTEM_PC_IP% >> "%DEPLOY_DIR%\crio_node.env"
echo. >> "%DEPLOY_DIR%\crio_node.env"
echo # MQTT Port >> "%DEPLOY_DIR%\crio_node.env"
echo MQTT_PORT=1883 >> "%DEPLOY_DIR%\crio_node.env"
echo. >> "%DEPLOY_DIR%\crio_node.env"
echo # Node ID >> "%DEPLOY_DIR%\crio_node.env"
echo NODE_ID=%NODE_ID% >> "%DEPLOY_DIR%\crio_node.env"

echo   Package created at %DEPLOY_DIR%
echo.

echo Step 2: Copying files to cRIO...
echo ----------------------------------------
echo   (You may be prompted for the admin password)
echo.

:: Create directory on cRIO and copy files
ssh admin@%CRIO_IP% "mkdir -p /home/admin/nisystem" 2>nul

:: Copy all files
scp -r "%DEPLOY_DIR%\*" admin@%CRIO_IP%:/home/admin/nisystem/

if errorlevel 1 (
    echo.
    echo ERROR: Failed to copy files to cRIO
    echo Make sure:
    echo   1. cRIO is powered on and connected
    echo   2. SSH is enabled on cRIO (via NI MAX or Web Config)
    echo   3. IP address is correct: %CRIO_IP%
    rd /s /q "%DEPLOY_DIR%" 2>nul
    exit /b 1
)

echo   Files copied successfully!
echo.

echo Step 3: Installing service on cRIO...
echo ----------------------------------------

:: Run install commands via SSH
ssh admin@%CRIO_IP% "cd /home/admin/nisystem && chmod +x install.sh && chmod +x crio_node.py"

:: Install pip packages
echo   Installing Python dependencies...
ssh admin@%CRIO_IP% "pip3 install -q paho-mqtt numpy 2>/dev/null || pip install -q paho-mqtt numpy 2>/dev/null || echo 'pip install skipped'"

:: Install systemd service
echo   Setting up systemd service...
ssh admin@%CRIO_IP% "sudo cp /home/admin/nisystem/crio_node.service /etc/systemd/system/ 2>/dev/null && sudo systemctl daemon-reload && sudo systemctl enable crio_node.service && sudo systemctl restart crio_node.service"

if errorlevel 1 (
    echo.
    echo WARNING: Automatic service setup may have failed.
    echo You can manually run on the cRIO:
    echo   cd /home/admin/nisystem
    echo   ./install.sh %NISYSTEM_PC_IP% %NODE_ID%
)

echo.
echo Step 4: Verifying installation...
echo ----------------------------------------

:: Give service time to start
timeout /t 3 /nobreak >nul

:: Check service status
ssh admin@%CRIO_IP% "systemctl is-active crio_node.service"

if errorlevel 1 (
    echo   Service status: UNKNOWN (check manually)
) else (
    echo   Service status: RUNNING
)

:: Cleanup temp directory
rd /s /q "%DEPLOY_DIR%" 2>nul

echo.
echo ================================================
echo   Deployment Complete!
echo ================================================
echo.
echo The cRIO node should now be:
echo   - Auto-detecting all hardware channels
echo   - Publishing values to MQTT at %NISYSTEM_PC_IP%:1883
echo   - Starting automatically on boot
echo.
echo Useful commands (run on cRIO via SSH):
echo   Check status:  systemctl status crio_node.service
echo   View logs:     journalctl -u crio_node.service -f
echo   Restart:       sudo systemctl restart crio_node.service
echo.
echo To SSH into cRIO:
echo   ssh admin@%CRIO_IP%
echo.

endlocal
