#!/bin/bash
#
# NISystem cRIO Node Installer
# Run this script on the cRIO to set up automatic startup
#
# Usage:
#   ./install.sh <NISYSTEM_PC_IP> [NODE_ID]
#
# Example:
#   ./install.sh 192.168.1.100
#   ./install.sh 192.168.1.100 crio-002
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=============================================="
echo "  NISystem cRIO Node Installer"
echo "=============================================="
echo ""

# Check arguments
if [ -z "$1" ]; then
    echo -e "${RED}Error: NISystem PC IP address required${NC}"
    echo ""
    echo "Usage: $0 <NISYSTEM_PC_IP> [NODE_ID]"
    echo ""
    echo "Example: $0 192.168.1.100"
    exit 1
fi

MQTT_BROKER="$1"
NODE_ID="${2:-crio-001}"
INSTALL_DIR="/home/admin/nisystem"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Configuration:"
echo "  NISystem PC (MQTT Broker): $MQTT_BROKER"
echo "  Node ID: $NODE_ID"
echo "  Install directory: $INSTALL_DIR"
echo ""

# Create install directory
echo -e "${YELLOW}Creating install directory...${NC}"
mkdir -p "$INSTALL_DIR"

# Copy Python script
echo -e "${YELLOW}Copying cRIO node service...${NC}"
cp "$SCRIPT_DIR/crio_node.py" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/crio_node.py"

# Create environment file
echo -e "${YELLOW}Creating configuration...${NC}"
cat > "$INSTALL_DIR/crio_node.env" << EOF
# cRIO Node Configuration
# Generated by install.sh on $(date)

# MQTT Broker - NISystem PC
MQTT_BROKER=$MQTT_BROKER

# MQTT Port
MQTT_PORT=1883

# Node ID
NODE_ID=$NODE_ID
EOF

# Configure journald to limit log size (prevents flash wear)
echo -e "${YELLOW}Configuring log rotation (50MB max)...${NC}"
mkdir -p /etc/systemd/journald.conf.d
cp "$SCRIPT_DIR/journald-nisystem.conf" /etc/systemd/journald.conf.d/nisystem.conf
systemctl restart systemd-journald

# Install systemd service
echo -e "${YELLOW}Installing systemd service...${NC}"
cp "$SCRIPT_DIR/crio_node.service" /etc/systemd/system/
systemctl daemon-reload

# Enable and start service
echo -e "${YELLOW}Enabling service to start on boot...${NC}"
systemctl enable crio_node.service

echo -e "${YELLOW}Starting service...${NC}"
systemctl start crio_node.service

# Wait a moment and check status
sleep 2

echo ""
echo "=============================================="
if systemctl is-active --quiet crio_node.service; then
    echo -e "${GREEN}SUCCESS! cRIO Node is running${NC}"
else
    echo -e "${RED}WARNING: Service may not be running correctly${NC}"
fi
echo "=============================================="
echo ""
echo "Useful commands:"
echo "  Check status:   systemctl status crio_node.service"
echo "  View logs:      journalctl -u crio_node.service -f"
echo "  Restart:        systemctl restart crio_node.service"
echo "  Stop:           systemctl stop crio_node.service"
echo ""
echo "Configuration file: $INSTALL_DIR/crio_node.env"
echo "Edit this file to change MQTT broker or node ID"
echo ""
echo "Log rotation: 50MB max, 7 days retention"
echo ""
