per_listener_settings true
listener 1883 127.0.0.1
allow_anonymous false
password_file config/mosquitto_passwd

listener 8883 0.0.0.0
cafile config/tls/ca.crt
certfile config/tls/server.crt
keyfile config/tls/server.key
allow_anonymous false
password_file config/mosquitto_passwd

listener 9002 127.0.0.1
protocol websockets
allow_anonymous true

log_dest stderr
log_type error
log_type warning
max_keepalive 120
message_size_limit 2097152
