#!/usr/bin/env python3
"""
Auto-generate MQTT credentials for NISystem zero-config deployment.

This script is called by start.bat on first run (or whenever credentials
are missing). It generates random passwords for the 'backend' and 'dashboard'
MQTT users, writes:
  - config/mqtt_credentials.json  (shared credential store)
  - config/mosquitto_passwd       (mosquitto password file, PBKDF2-SHA512)
  - dashboard/.env.local          (Vite env vars for dashboard)

Idempotent: skips if config/mqtt_credentials.json already exists.
"""

import base64
import hashlib
import json
import os
import secrets
import sys

# Resolve paths relative to the project root (parent of scripts/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRED_FILE = os.path.join(PROJECT_ROOT, 'config', 'mqtt_credentials.json')
PASSWD_FILE = os.path.join(PROJECT_ROOT, 'config', 'mosquitto_passwd')
ENV_FILE = os.path.join(PROJECT_ROOT, 'dashboard', '.env.local')


def generate_password(length: int = 24) -> str:
    """Generate a cryptographically secure random password."""
    return secrets.token_urlsafe(length)


def hash_mosquitto_password(password: str, iterations: int = 101) -> str:
    """
    Generate a mosquitto-compatible PBKDF2-SHA512 password hash.

    Format: $7$<iterations>$<base64(salt)>$<base64(hash)>

    This matches the output of `mosquitto_passwd -b` (mosquitto 2.0+).
    """
    salt = os.urandom(12)
    dk = hashlib.pbkdf2_hmac(
        'sha512',
        password.encode('utf-8'),
        salt,
        iterations,
        dklen=64
    )
    salt_b64 = base64.b64encode(salt).decode('ascii')
    hash_b64 = base64.b64encode(dk).decode('ascii')
    return f"$7${iterations}${salt_b64}${hash_b64}"


def write_mosquitto_passwd(users: dict) -> None:
    """Write mosquitto password file with hashed credentials."""
    lines = []
    for username, password in users.items():
        hashed = hash_mosquitto_password(password)
        lines.append(f"{username}:{hashed}")

    with open(PASSWD_FILE, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    # Restrict file permissions on non-Windows
    if os.name != 'nt':
        os.chmod(PASSWD_FILE, 0o600)


def write_dashboard_env(username: str, password: str) -> None:
    """Write dashboard .env.local with MQTT credentials."""
    content = (
        "# Auto-generated by scripts/mqtt_credentials.py\n"
        "# Do not edit — regenerate by deleting config/mqtt_credentials.json and restarting\n"
        f"VITE_MQTT_USERNAME={username}\n"
        f"VITE_MQTT_PASSWORD={password}\n"
    )
    with open(ENV_FILE, 'w') as f:
        f.write(content)


def main() -> int:
    # Idempotent: skip if credentials already exist
    if os.path.exists(CRED_FILE):
        print(f"[MQTT] Credentials already exist: {CRED_FILE}")
        return 0

    print("[MQTT] Generating MQTT credentials (first-run setup)...")

    # Generate random passwords
    backend_pass = generate_password()
    dashboard_pass = generate_password()

    creds = {
        'backend': {'username': 'backend', 'password': backend_pass},
        'dashboard': {'username': 'dashboard', 'password': dashboard_pass},
    }

    # 1. Write credential store (JSON)
    os.makedirs(os.path.dirname(CRED_FILE), exist_ok=True)
    with open(CRED_FILE, 'w') as f:
        json.dump(creds, f, indent=2)
    if os.name != 'nt':
        os.chmod(CRED_FILE, 0o600)
    print(f"[MQTT]   Credentials saved: {CRED_FILE}")

    # 2. Write mosquitto password file (PBKDF2-SHA512 hashes)
    write_mosquitto_passwd({
        'backend': backend_pass,
        'dashboard': dashboard_pass,
    })
    print(f"[MQTT]   Password file saved: {PASSWD_FILE}")

    # 3. Write dashboard .env.local
    write_dashboard_env('dashboard', dashboard_pass)
    print(f"[MQTT]   Dashboard env saved: {ENV_FILE}")

    print("[MQTT] Credentials generated successfully.")
    print("[MQTT] To regenerate: delete config/mqtt_credentials.json and restart.")
    return 0


def export_peer_bridge_config(peer_ip: str) -> str:
    """
    Generate a Mosquitto bridge config snippet for dual-PC redundancy.

    Reads the 'backend' password from mqtt_credentials.json and returns
    a ready-to-paste bridge config block pointing at this PC's broker.
    """
    if not os.path.exists(CRED_FILE):
        return "ERROR: No credentials found. Run the system once to generate them."

    with open(CRED_FILE) as f:
        creds = json.load(f)

    backend_pass = creds['backend']['password']

    return (
        f"# Peer bridge config — paste into the OTHER PC's mosquitto.conf\n"
        f"# Generated by scripts/mqtt_credentials.py\n"
        f"connection peer-bridge\n"
        f"address {peer_ip}:8883\n"
        f"topic # both 2\n"
        f"bridge_cafile config/tls/ca.crt\n"
        f"bridge_certfile config/tls/server.crt\n"
        f"bridge_keyfile config/tls/server.key\n"
        f"remote_username backend\n"
        f"remote_password {backend_pass}\n"
        f"cleansession true\n"
        f"start_type automatic\n"
        f"restart_timeout 5\n"
        f"notifications true\n"
        f"notification_topic nisystem/bridge/status\n"
    )


if __name__ == '__main__':
    sys.exit(main())
